- name: add gitlab runner package repository
  become: yes
  shell: curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash

- name: install the latest gitlab runner
  become: yes
  shell: export GITLAB_RUNNER_DISABLE_SKEL=true; sudo -E apt-get install gitlab-runner
